// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['MAPS_API_KEY'] ?? '',
    appId: '1:740649181384:web:38fa411dc7560a22f1c5fd',
    messagingSenderId: '740649181384',
    projectId: 'floodguardai-37df5',
    authDomain: 'floodguardai-37df5.firebaseapp.com',
    storageBucket: 'floodguardai-37df5.firebasestorage.app',
    measurementId: 'G-D7QZ1F39V0',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['MAPS_API_KEY'] ?? '',
    appId: '1:740649181384:android:29b4519101b14037f1c5fd',
    messagingSenderId: '740649181384',
    projectId: 'floodguardai-37df5',
    storageBucket: 'floodguardai-37df5.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['MAPS_API_KEY'] ?? '',
    appId: '1:740649181384:ios:5ccfbf3e242750f5f1c5fd',
    messagingSenderId: '740649181384',
    projectId: 'floodguardai-37df5',
    storageBucket: 'floodguardai-37df5.firebasestorage.app',
    iosBundleId: 'com.example.floodguardAi',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['MAPS_API_KEY'] ?? '',
    appId: '1:740649181384:ios:5ccfbf3e242750f5f1c5fd',
    messagingSenderId: '740649181384',
    projectId: 'floodguardai-37df5',
    storageBucket: 'floodguardai-37df5.firebasestorage.app',
    iosBundleId: 'com.example.floodguardAi',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['MAPS_API_KEY'] ?? '',
    appId: '1:740649181384:web:6ef5af50f670a5c4f1c5fd',
    messagingSenderId: '740649181384',
    projectId: 'floodguardai-37df5',
    authDomain: 'floodguardai-37df5.firebaseapp.com',
    storageBucket: 'floodguardai-37df5.firebasestorage.app',
    measurementId: 'G-SNT46K5J75',
  );
}
